id: jms_trigger_activemq
namespace: io.kestra.examples

description: |
  Trigger a flow when a message arrives on an ActiveMQ queue.

  Prerequisites:
  - Build: ./gradlew build -x test
  - Start: docker-compose -f src/examples/docker/docker-compose.yml up
  - Send messages using jms_produce_activemq.yaml to trigger this flow

tasks:
  - id: process_message
    type: io.kestra.plugin.core.log.Log
    message: "Received message: {{ trigger.data }}"

  - id: log_metadata
    type: io.kestra.plugin.core.log.Log
    message: |
      Message ID: {{ trigger.messageId }}
      Timestamp: {{ trigger.timestamp }}

triggers:
  - id: watch_queue
    type: io.kestra.plugin.jms.JMSRealtimeTrigger
    connectionFactoryConfig:
      type: DIRECT
      connectionFactoryClass: org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
      connectionProperties:
        brokerURL: tcp://activemq:61616
        user: admin
        password: admin
    destination:
      destinationName: kestra.example.queue
      destinationType: QUEUE
    serdeType: STRING
