version: "3.8"
name: kestra-jms-sonicmq

services:
  kestra:
    image: kestra/kestra:v1.0.3
    #build:
    #  context: .
    #dockerfile: Dockerfile
    #  command: server local
    entrypoint: /bin/sh -c "
      cd /app/ && \
      ./kestra server local"
    ports:
      - "8080:8080"
      - "7999:7999"
    volumes:
      # Mount only the JMS plugin JAR (version-neutral name created by build)
      - ../../../build/libs/plugin-jms-docker.jar:/app/plugins/plugin-jms.jar:ro
      # Mount SonicMQ libs - replace path with your SonicMQ installation
      - /Users/stefan/sonic/12.0.4/MQ12.0/lib/:/app/plugins/jms-libs/:ro
    #environment:
    #   - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7999
