version: "3.8"
name: kestra-jms-activemq

# Default Docker Compose setup with ActiveMQ Artemis (quick-start)
#
# USAGE:
# 1. Build the plugin (skips tests to avoid port conflicts):
#    ./gradlew build -x test
#
# 2. Start the services:
#    docker-compose -f src/examples/docker/docker-compose.yml up
#
# 3. Access:
#    - Kestra UI: http://localhost:8080
#    - ActiveMQ Console: http://localhost:8161 (admin/admin)

services:
  activemq:
    image: apache/activemq-artemis:latest
    ports:
      - "61616:61616"  # JMS/OpenWire port
      - "8161:8161"    # Web console
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161/console/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kestra:
    image: kestra/kestra:v1.0.3
    entrypoint: /bin/sh -c "
      cd /app/ && \
      ./kestra server local"
    ports:
      - "8080:8080"      # Kestra UI
      - "7999:7999"      # Debug port (optional)
    volumes:
      # Mount only the JMS plugin JAR (version-neutral name created by build)
      - ../../../build/libs/plugin-jms-docker.jar:/app/plugins/plugin-jms.jar:ro
      # Mount ActiveMQ Artemis client libs (automatically copied during build)
      - ../../../build/test-libs/:/app/plugins/jms-libs/:ro
    depends_on:
      activemq:
        condition: service_healthy
    #environment:
    #   - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7999
